swagger: "2.0"
info:
  version: "1.0.0"
  title: "Tetris Score Analyzer"
  description: "Analyzes Tetris games from the Tetris World Championships"
  termsOfService: "http://swagger.io.terms"
  contact:
    name: "Tetris Score Analyzer"
    email: "zwlevy@iu.edu"
  license:
    name: "Apache 2.0"
    url: "http:///www.apache.org/licenses/LICENSE-2.0"
host: "localhost:8080"
basePath: "/cloudmesh/ai/tetris"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /lin_reg/download/<output>:
    get:
      operationId: linear_regressor.download
      produces:
        - "application/json"
      responses:
        "200":
          description: "lin_reg download OK"
          schema: {}

  /lin_reg/read:
    get:
      operationId: linear_regressor.read_csv
      produces:
        - "application/txt"
      responses:
        "200":
          description: "lin_reg read OK"
          schema: {}

  /lin_reg/analyze:
    get:
      operationId: linear_regressor.linear_regression
      produces:
        - "application/png"
      responses:
        "200":
          description: "lin_reg analysis OK"
          schema: {}

  /dt/download/<output>:
    get:
      operationId: data_tree.download
      produces:
        - "application/json"
      responses:
        "200":
          description: "dt read OK"
          schema: {}

  /dt/analyze:
    get:
      operationId: data_tree.data_tree
      produces:
        - "application/png"
      responses:
        "200":
          description: "dt analysis OK"
          schema: {}
