swagger: "2.0"
info:
  version: "1.0.0"
  description: "Send-recieve data from a Tetris game and analyze results"
  termsOfService: "http://swagger.io.terms/"
  contact:
    name: "Tetris Machine Learning Score Analysis RESTful Server"
  license: "Apache"
host: "localhost:8080"
basePath: "/project"
shemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /data/output/<output>:
    get:
      operationId: data.download
      description: "Downloads data form url"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Data info"
          schema: {}
